name: "MasterInfo"
version: "1.3"
main: "vb.$masterinfo.PluginMain"
api-version: 1.13
author: "MasterRecording"
description: "Este plugin es creado por Masterrecording para el servidor MasterHCF.cf"
commands:
  info:
    aliases: [información]
    description: "Este comando te muestra todo lo que necesitas saber del servidor!"
  MasterInfo:
    aliases: [masterinfo]
permissions:
